  name: CI/CD Pipeline
  on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 21
          uses: actions/setup-java@v2
          with:
            java-version: '21'
        - name: Build with Maven
          run: mvn clean install
        - name: Run Tests
          run: mvn test
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to Server
          run: echo "Deploy step (custom implementation here)"