name: CI/CD Pipeline - orderservice

on:
  push:
    branches:
      - master
    paths:
      - 'orderservice/**'
  pull_request:
    branches:
      - master
    paths:
      - 'orderservice/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' 

      - name: Make mvnw executable
        run: chmod +x mvnw
        working-directory: orderservice

      - name: Build and run tests (fail on warnings)
        run: ./mvnw clean verify -B -Dmaven.compiler.failOnWarning=true
        working-directory: orderservice
        

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: orderservice/target/surefire-reports/
       

      - name: Upload code coverage (JaCoCo)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: orderservice/target/site/jacoco/
        









