name: CI/CD Pipeline - orderservice

on:
  push:
    branches:
      - master
    paths:
      - 'orderservice/**'
  pull_request:
    branches:
      - master
    paths:
      - 'orderservice/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged  
        ports:
          - 5432:5432
          - 9092:9092

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker is running
        run: |
          docker version
          docker info

      - name: Make mvnw executable
        run: chmod +x mvnw
        working-directory: orderservice

      - name: Build and run tests (with Testcontainers)
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          TESTCONTAINERS_RYUK_DISABLED: false
        run: ./mvnw clean verify -B -Dmaven.compiler.failOnWarning=true
        working-directory: orderservice

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: orderservice/target/surefire-reports/

      - name: Upload code coverage (JaCoCo)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: orderservice/target/site/jacoco/














